### ISSUE TITLE
Faced a problem with the minimum platform version in MSAL

### ISSUE THREAD

**Issue by Prakhar-Swarnakar** [Azure/azure-maps-ios-sdk-distribution#5]
Hey,
I was trying to build a basic application and tried importing this SDK.
Referring to Azure Documentation: https://learn.microsoft.com/en-us/azure/azure-maps/quick-ios-app

Faced a problem with the minimum platform version stating
"The package product 'MSAL' requires minimum platform version 14.0 for the iOS platform, but this target supports 13.0"
whereas the platform is config to iOS version 16 

<img width="1348" alt="Screenshot 2023-06-06 at 1 04 27 PM" src="https://github.com/Azure/azure-maps-ios-sdk-distribution/assets/57248880/aac95694-0903-4c24-b2d4-43930a77363e">

**Comment by ambientlight** [comment]
fixed via #4
